name: AUTO DATA SCRAPER

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalışır (daha makul)
    # - cron: '*/5 * * * *'  # Her 5 dakikada bir (test için)
  workflow_dispatch:  # Manuel tetikleme imkanı sağlar

jobs:
  scrape:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # En güncel versiyon
          
      - name: Set up Node.js
        uses: actions/setup-node@v4  # En güncel versiyon
        with:
          node-version: '20.x'  # Node.js 20 LTS kullan
          
      - name: Install dependencies
        run: |
          npm install  # package-lock.json olmadığı için npm install kullan
          
      - name: Run scraper
        run: |
          echo "Scraper başlatılıyor..."
          node allpages.js
          echo "Scraper tamamlandı."
          
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Değişiklikler tespit edildi:"
            git status --short
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "Hiç değişiklik yok."
          fi
          
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "codermert@bk.ru"
          git config --local user.name "codermert"
          git add models.json
          git commit -m "🕰 Otomatik Veri Güncelleme » $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push
          
      - name: Upload artifact (backup)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data-${{ github.run_number }}
          path: models.json
          retention-days: 7
